### ISSUE TITLE
On Post Create TinyMce Initialize error 

### ISSUE THREAD

**Issue by damulhan** [yeesoft/yii2-yee-cms#57]
On post create i got TinyMce Error. 

But on page create I worked. 

I can't know what is the difference of codes between two modules. 

`
jquery.js:3860 jQuery.Deferred exception: obj.size is not a function TypeError: obj.size is not a function
    at jQuery.fn.init.$.fn.magicSuggest (http://10.1.11.73/admin/assets/940e2185/magicsuggest-min.js:1:21458)
    at HTMLDocument.<anonymous> (http://10.1.11.73/admin/post/create:252:43)
    at mightThrow (http://10.1.11.73/admin/assets/598c40f7/jquery.js:3583:29)
    at process (http://10.1.11.73/admin/assets/598c40f7/jquery.js:3651:12) undefined

jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
jquery.js:3869 Uncaught TypeError: obj.size is not a function
    at jQuery.fn.init.$.fn.magicSuggest (magicsuggest-min.js:1)
    at HTMLDocument.<anonymous> (create:252)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
`

**Comment by neoacevedo** [comment]
It's an issue on **magicsuggest** extension. 

Try uncompressing this zip file: [magicsuggest.zip](https://github.com/yeesoft/yii2-yee-cms/files/2099131/magicsuggest.zip) into vendor/nicolasbize/magicsuggest/ to replace both JS files.

In short words: _.size_ is not a function for jQuery >3.1

These files changes _obj.size()_ to _obj.length_
